#include <vmath.hpp>
#include <list>

class lsystem
{
public:

    /// Parse given XML file, evaluate rules, populate member curve
    void Evaluate(const char* filename, int seed = 0);
    
    struct CurvePoint {
        vmath::Point3 P;
        vmath::Vector3 N;
    };
    
    typedef std::list<CurvePoint*> Curve;

    /// The curve generated by the L-system
    const Curve& GetCurve() const { return _curve; }

    ~lsystem();
    
private:
    Curve _curve;    
};

