# Clean:
#  > scons -c
#
# Debug configuration:
#  > scons debug=1
#
# Parallel build:
#  > scons -j 4

import sys
import os

source = Split("""
  main.cpp
  lsystem.cpp
  pugixml.cpp
  diagnostic.cpp
  tinythread.cpp
""")

env = Environment(ENV = os.environ)

env.Program('Ribbon', source)
env.Append(CPPPATH = '.')

if ARGUMENTS.get('debug', 0):
     env.Append(CCFLAGS = '-g')

