include $(GOROOT)/src/Make.inc

TARG=curve

GOFILES=\
    lsystem.go\
    stack.go\
    curve.go\

CLEANFILES += \
    *.slo \
    stats.xml \
    debug.rib \

LDIMPORTS += -r $(RMANTREE)/lib

include $(GOROOT)/src/Make.cmd
